"""FastAPI + HTMX dashboard — the Python instance's web app.

Mirrors the R Shiny dashboard (sl_dashboard) tab for tab. Charts are the very
same matplotlib figures the package already renders, streamed as PNG, so the
R<->Python chart mirror and the parity harness keep protecting them -- the web
layer adds no new plotting code.

    python launch.py dashboard [--port 8000]
    uvicorn webapp.app:app --reload      # from python/
"""
from __future__ import annotations

import io
import os
import threading
import time
from html import escape as html_escape
from pathlib import Path

import matplotlib
from fastapi import FastAPI, Query, Request
from fastapi.responses import HTMLResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

matplotlib.use("Agg")

import sleepermetrics as sm  # noqa: E402
from sleepermetrics import draft, metrics, plots, scoring, summaries  # noqa: E402
# Aliased: the `/report` route function below would otherwise shadow the module.
from sleepermetrics import report as sm_report  # noqa: E402

BASE = Path(__file__).resolve().parent
ROOT = BASE.parent.parent                       # repo root
PLAYOFF_DIR = os.environ.get("SLEEPERMETRICS_PLAYOFFS", str(ROOT / "playoffs"))
DEFAULT_LEAGUE = os.environ.get("SLEEPERMETRICS_LEAGUE", "1252770181306929152")
TTL = int(os.environ.get("SLEEPERMETRICS_TTL", "900"))   # cache seasons 15 min

app = FastAPI(title="Sleeper League Analytics")
app.mount("/static", StaticFiles(directory=BASE / "static"), name="static")
tpl = Jinja2Templates(directory=str(BASE / "templates"))


def asset_v() -> str:
    """Cache-busting stamp for the static assets (style.css + builder.js).

    Browsers hold onto these hard: a stale stylesheet silently strips the
    report's layout (a grid degrades to run-together text), and a stale
    builder.js silently runs an old bracket editor (its team dropdowns stop
    populating). One `?v=` on both URLs is the newest mtime across both files,
    so editing EITHER is always picked up -- don't narrow this back to one file.
    """
    newest = 0
    for name in ("style.css", "builder.js"):
        try:
            newest = max(newest, int((BASE / "static" / name).stat().st_mtime))
        except OSError:
            pass
    return str(newest)


@app.middleware("http")
async def _stamp_asset_version(request: Request, call_next):
    """Tell an already-open page which stylesheet build the server is on.

    `?v=<mtime>` only helps on a FULL page load, and this is an htmx app: a tab
    click swaps #panel and never re-reads the <link> in <head>. So a page left
    open across a CSS edit keeps serving the old stylesheet indefinitely, and
    markup relying on a new rule renders unstyled -- grid rows collapse to
    inline spans separated by a single space. The client compares this header on
    every swap and re-points the link when it differs.
    """
    resp = await call_next(request)
    resp.headers["X-Asset-V"] = asset_v()
    return resp


def _md(text: str):
    """Render the summaries' small markdown subset (###, -, **bold**, `code`).

    The summaries are generated by us and use exactly these four constructs, so a
    full markdown dependency would be dead weight. The input is html-escaped
    first, so marking the result safe only trusts the tags this function emits --
    never the data.
    """
    import html
    import re

    from markupsafe import Markup
    out, ul = [], False
    for line in html.escape(text or "").splitlines():
        line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
        line = re.sub(r"`(.+?)`", r"<code>\1</code>", line)
        if line.startswith("### "):
            if ul:
                out.append("</ul>")
                ul = False
            out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("- "):
            if not ul:
                out.append("<ul>")
                ul = True
            out.append(f"<li>{line[2:]}</li>")
        elif line.strip():
            if ul:
                out.append("</ul>")
                ul = False
            out.append(f"<p>{line}</p>")
    if ul:
        out.append("</ul>")
    return Markup("\n".join(out))


tpl.env.filters["md"] = _md


def pd_notna(v) -> bool:
    import pandas as pd
    return bool(pd.notna(v))


def records(df) -> list[dict]:
    """`df.to_dict("records")` with every missing value as None, not NaN.

    Templates guard missing values with `is not none` / `or`, and **pandas NaN
    defeats both** -- it is neither None nor falsey, so the guard passes and the
    cell renders the literal "nan" (or "+nan" once a format string has been
    applied to it). Scrubbing at this boundary is what makes those guards mean
    what they read as, so hand template rows through here rather than calling
    `to_dict` directly.
    """
    import pandas as pd

    def clean(v):
        if v is None:
            return None
        try:
            # Covers NaN, NaT and pd.NA alike; a list/array argument makes
            # pd.isna return an array, whose truth value raises -- keep those.
            return None if pd.isna(v) else v
        except (TypeError, ValueError):
            return v

    return [{k: clean(v) for k, v in row.items()} for row in df.to_dict("records")]


def _avatar_map(s) -> dict:
    """`{user_name: avatar_url}` for a season, so tab tables/tiles can hang a
    manager's team portrait beside their name (the same identity the Career
    Managers panel shows). Reads the season's `accounts` frame -- the account
    avatar, falling back to the custom team picture. Missing/empty avatars are
    simply omitted, so a name with no portrait renders as plain text.
    """
    import pandas as pd
    acc = getattr(s, "accounts", None)
    if acc is None or getattr(acc, "empty", True) or "user_name" not in acc:
        return {}
    out: dict = {}
    for r in acc.itertuples(index=False):
        name = getattr(r, "user_name", None)
        if not (name is not None and pd.notna(name)):
            continue
        for col in ("avatar_url", "team_avatar_url"):
            v = getattr(r, col, None)
            if v is not None and pd.notna(v) and str(v).strip():
                out[str(name)] = str(v)
                break
    return out


def _grouped_rules(settings: dict) -> list[tuple[str, list[dict]]]:
    """The point-calculation chart as [(group, [rule, ...])], in plain English.

    Sleeper keys the chart by stat code (`bonus_rec_te`); a manager reading why
    they lost should not have to know what that means. statnames does the
    translating -- shared with the R dashboard and parity-checked against it.
    """
    d = sm.scoring_readable(settings)
    return [(g, records(rows)) for g, rows in d.groupby("group", sort=False)]

# Tab order follows how a season is actually built and played, so the middle of
# the rail reads as a causal chain rather than an arbitrary list:
#   overview/weekly  -- what happened (the landing view, then it week by week)
#   draft            -- where every roster came from
#   roster           -- what those rosters became
#   transactions     -- how they were changed
#   coaching         -- how they were deployed
#   playoffs         -- how the season ended (after every regular-season tab,
#                       which now matters: the two are scoped apart)
#   career/report    -- beyond this season, then the thing you take away
# Draft used to sit AFTER transactions, i.e. after the tab that modifies the
# rosters the draft created, and coaching sat second, interrupting the summary
# view with the most granular "why" tab in the app.
TABS = [
    ("overview", "Season overview"), ("weekly", "Weekly trends"),
    ("draft", "Draft"), ("roster", "Roster & positions"),
    ("transactions", "Transactions"), ("coaching", "Coaching & scoring"),
    ("playoffs", "Playoffs"), ("career", "Career"),
    ("report", "Season report"),
]

# --- cache ----------------------------------------------------------------
# Assembling a league is many API calls, so hold it briefly rather than rebuild
# it on every tab switch. Charts are cheap to redraw from the cached frames.
_cache: dict = {}

# Ad-hoc bracket cache: a user-supplied / rolled-back bracket, scored once and
# held under a content-addressed token so the tab and its PNG charts (which are
# separate <img> requests that can't carry a POST body) can all reference the
# same Playoff via ?bracket=<token>. Keyed by a hash of the config, so identical
# brackets share a token and it is idempotent; ephemeral (TTL) and per-content,
# so different visitors never clobber each other -- persistence is client-side
# (localStorage + download), the server stays read-only.
_bracket_cache: dict = {}
_BRACKET_TTL = 3600


def _bracket_token(config: dict) -> str:
    import hashlib
    import json as _json
    raw = _json.dumps(config, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return hashlib.sha1(raw).hexdigest()[:16]


def _cache_bracket(config: dict):
    """Score a config into a Playoff and cache it; returns (token, Playoff)."""
    tok = _bracket_token(config)
    hit = _bracket_cache.get(tok)
    if hit and time.time() - hit["at"] < _BRACKET_TTL:
        return tok, hit["playoff"]
    p = sm.playoff(config, validate=False)
    _bracket_cache[tok] = {"config": config, "playoff": p, "at": time.time()}
    return tok, p


def _bracket_from_token(token: str | None):
    """The cached Playoff for a token, or None if absent/expired."""
    hit = _bracket_cache.get(token) if token else None
    if hit and time.time() - hit["at"] < _BRACKET_TTL:
        return hit["playoff"]
    return None


def league_data(league_id: str, fresh: bool = False) -> dict:
    hit = _cache.get(league_id)
    if hit and not fresh and time.time() - hit["at"] < TTL:
        return hit
    seasons = sm.apply_playoffs(sm.seasons(league_id), PLAYOFF_DIR)
    # Only this league's brackets -- a stored 2025.json belongs to a league, not
    # to the number 2025, so another league must not inherit DDBM's playoffs.
    playoffs = sm.load_playoffs(
        PLAYOFF_DIR, league_ids=[s.league_id for s in seasons.values()])
    d = {"at": time.time(), "seasons": seasons, "playoffs": playoffs,
         "names": list(seasons)}
    _cache[league_id] = d
    return d


def pick(league_id: str, season: str | None, fresh: bool = False):
    d = league_data(league_id, fresh)
    key = season if season in d["seasons"] else d["names"][-1]
    return d, d["seasons"][key], key


# matplotlib's pyplot state is global and not thread-safe, and the chart theme
# is a module-level token that a request flips before drawing -- so every render
# path holds this lock, or two concurrent requests could draw on each other's
# theme (a dark chart saved with a light facecolor, say).
_render_lock = threading.Lock()


def png(fig) -> Response:
    buf = io.BytesIO()
    # Match the saved facecolor to the active theme so a dark chart isn't matted
    # onto a white rectangle. plots.T is already the theme set under the lock.
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight",
                facecolor=plots.T["bg"])
    matplotlib.pyplot.close(fig)
    # Cacheable per (url incl. theme + bust): the browser reuses charts across
    # tab visits instead of re-fetching every switch. `bust` changes on a live
    # re-score, so a refreshed week is never served stale.
    return Response(buf.getvalue(), media_type="image/png",
                    headers={"Cache-Control": "private, max-age=120"})


# --- chart registry -------------------------------------------------------
# name -> (scope, fn). Season charts take a Season; career/playoff charts take
# the whole league. Everything comes straight from plots.py.
SEASON_CHARTS = {
    "standings": plots.plot_standings, "luck": plots.plot_luck,
    "efficiency": plots.plot_efficiency, "consistency": plots.plot_consistency,
    "pf_pa": plots.plot_pf_pa, "table_position": plots.plot_table_position,
    "team_points": plots.plot_team_points,
    "allplay": plots.plot_allplay, "power_rank": plots.plot_power_rank,
    "manager_profile": plots.plot_manager_profile,
    "position_scoring": plots.plot_position_scoring,
    "roster_heatmap": plots.plot_roster_heatmap,
    "starter_bench": plots.plot_starter_bench,
    "position_box": plots.plot_position_box,
    "roster_counts": plots.plot_roster_counts,
    "trade_performance": plots.plot_trade_performance,
    "waiver_performance": plots.plot_waiver_performance,
    "boom_bust": plots.plot_boom_bust, "sos": plots.plot_sos,
    "schedule_swap": plots.plot_schedule_swap,
    "draft_value": plots.plot_draft_value, "draft_grades": plots.plot_draft_grades,
}


# Manager-scoped charts take (season, manager) instead of just a season. They
# back the manager report's sections, so this registry must stay in step with
# the "season+manager" entries in report._CHART_FNS.
# Charts scoped to ONE week. They take (season, week), so they need the `week`
# query param -- a bare /chart/<name> would silently draw the wrong week.
WEEK_CHARTS = {
    "week_matchups": plots.plot_week_matchups,   # dumbbell per game
    "week_luck": plots.plot_week_luck,           # PF vs PA, split by the tie line
    "week_race": plots.plot_week_race,           # table position, weeks 1..N
}

MANAGER_CHARTS = {
    "mgr_score_band": plots.plot_mgr_score_band,
    "mgr_optimal": plots.plot_mgr_optimal,
    "mgr_margins": plots.plot_mgr_margins,
}


# Per-chart insight + placement, so a grid of PNGs reads as a narrated set rather
# than a wall of graphics. `cap` is the one-line insight rendered as the figure's
# caption (the chart already carries its own baked-in title/subtitle, so this
# frames *why it's here*, not how to read the axes). `wide` spans the full grid
# row -- reserved for the genuinely wide-aspect charts (measured from their
# figsize), so a 15x6 chart isn't crushed into a half-width column. Consumed by
# the `_chartmacro.html` macro; unknown keys fall back to a plain figure.
CHART_META = {
    # Season / overview
    "standings": {"cap": "Where each team stands — record first, total points breaking ties."},
    "power_rank": {"cap": "Scoring, all-play, recent form and lineup efficiency blended into one number."},
    "allplay": {"cap": "The record a team would carry if it played the whole league every week — schedule removed."},
    "luck": {"cap": "Points scored set against the record they actually bought — a gap is the schedule helping or hurting."},
    "team_points": {"cap": "Weekly points stacked — total output and how steady it was.", "wide": True},
    "sos": {"cap": "How strong a schedule each team drew — their opponents' average points."},
    "schedule_swap": {"cap": "Each team's record replayed under every rival's schedule."},
    # Coaching
    "efficiency": {"cap": "Points started as a share of the best legal lineup available — the cost of the decision."},
    "consistency": {"cap": "Week-to-week spread — a short bar is dependable, a long one runs hot and cold."},
    "pf_pa": {"cap": "What each team scored against what it faced."},
    "boom_bust": {"cap": "Each manager's ceiling and floor around their average week."},
    # Roster
    "position_scoring": {"cap": "Started points by position and each slot's share of the total."},
    "roster_counts": {"cap": "The average roster shape each manager carried."},
    "roster_heatmap": {"cap": "Where each team's scoring lived — points by manager and position."},
    "starter_bench": {"cap": "Started points against what sat on the bench, per manager.", "wide": True},
    "position_box": {"cap": "The scoring spread at each position — good weeks against bad."},
    # Transactions
    "manager_profile": {"cap": "Moves, trades and drops per manager, with a lineup-IQ score."},
    "trade_performance": {"cap": "Every traded player by the points he returned while rostered."},
    "waiver_performance": {"cap": "Every waiver or free-agent pickup by points returned while rostered."},
    # Draft
    "draft_value": {"cap": "Started points each pick returned to the team that drafted him."},
    "draft_grades": {"cap": "Value weighed against draft slot — a late steal grades above a costly early miss."},
    # Career
    "career": {"cap": "Cumulative record and points across every season on record."},
    "trajectory": {"cap": "Where each manager finished, season by season."},
    "head_to_head": {"cap": "All-time record of every manager against every other."},
    "loyalty": {"cap": "The players a manager keeps re-rostering year after year."},
    # Week (used where these render via the macro, e.g. the season-so-far race)
    "week_race": {"cap": "Table position after each week — where lines cross, the lead changed."},
}
tpl.env.globals["CHART_META"] = CHART_META


@app.get("/chart/{name}")
def chart(name: str, league: str = DEFAULT_LEAGUE, season: str | None = None,
          matchup: str | None = None, scope: str = "title",
          theme: str = "light", manager: str | None = None,
          week: str | None = None, bracket: str | None = None,
          _: str | None = None):
    d, s, key = pick(league, season)
    # A custom / rolled-back bracket (token) overrides this season's committed
    # one for every playoff chart, so the whole tab reflects it consistently.
    pov = _bracket_from_token(bracket)
    # Build + save under the lock, with the requested theme active, so the
    # structural palette and the saved facecolor can't be crossed by a
    # concurrent request drawing in the other theme.
    with _render_lock:
        plots.set_chart_theme(theme)
        if name in SEASON_CHARTS:
            return png(SEASON_CHARTS[name](s))
        if name in WEEK_CHARTS:
            # Default to the latest scored week, matching the tab's own default.
            try:
                wk = int(week) if week else s.last_week
            except ValueError:
                wk = s.last_week
            return png(WEEK_CHARTS[name](s, wk))
        if name in MANAGER_CHARTS:
            # The chart draws its own "no data" panel for a manager this season
            # doesn't have, so an unknown scope degrades instead of 500ing.
            return png(MANAGER_CHARTS[name](s, manager or ""))
        if name == "career":
            return png(plots.plot_career(d["seasons"]))
        if name == "trajectory":
            return png(plots.plot_trajectory(d["seasons"]))
        if name == "loyalty":
            return png(plots.plot_loyalty(d["seasons"]))
        if name == "head_to_head":
            return png(plots.plot_head_to_head(d["seasons"]))
        # Playoff analytics come in two spans. The bare keys follow the selected
        # season (the Playoffs tab); the `_all` keys aggregate every stored
        # bracket (the Career tab). Same functions either way -- they aggregate
        # whatever brackets they are given, and _po_span labels the result -- so
        # the span is chosen here, by which dict gets passed.
        # The token bracket (if any) is this season's active playoff for the
        # season-scoped charts; the `_all` career charts always use every stored
        # bracket and ignore it.
        p_season = pov or d["playoffs"].get(key)
        po = {key: p_season} if p_season is not None else {}
        if name == "playoff_stats":
            return png(plots.plot_playoff_stats(po, scope))
        if name == "playoff_players":
            return png(plots.plot_playoff_players(po, scope=scope))
        if name == "clutch":
            return png(plots.plot_clutch({key: d["seasons"][key]}, po, scope))
        if name == "playoff_stats_all":
            return png(plots.plot_playoff_stats(d["playoffs"], scope))
        if name == "playoff_players_all":
            return png(plots.plot_playoff_players(d["playoffs"], scope=scope))
        if name == "clutch_all":
            return png(plots.plot_clutch(d["seasons"], d["playoffs"], scope))
        if name == "bracket":
            if p_season is None:
                return Response(status_code=404)
            # Bye/idle nodes carry the team's real weekly score for reference,
            # so they read as a number rather than a dash.
            return png(plots.plot_playoff_bracket(p_season, sm.reference_scores(s)))
        if name == "playoff_matchup":
            if p_season is None:
                return Response(status_code=404)
            mid = matchup or p_season.config.get("final")
            return png(plots.plot_playoff_matchup(p_season, mid))
    return Response(status_code=404)


# --- pages ----------------------------------------------------------------
@app.get("/", response_class=HTMLResponse)
def home(request: Request, league: str = DEFAULT_LEAGUE):
    """The landing / home page: a league-id field that leads into the analytics.

    Deliberately does no league load -- it stays instant. The field is
    temporarily pre-filled with the Dank Soupers (DDBM) league id so the default
    path is one click; the form GET-submits to /dashboard, which is where the
    season analytics actually live.
    """
    return tpl.TemplateResponse(request, "home.html", {
        "league": league, "asset_v": asset_v(),
    })


# The analytics link reads `/league=<id>` (no `/dashboard?` query) -- a literal
# `league=` prefix on the path segment, with the id captured after it. `/dashboard`
# stays as a graceful fallback for the landing form when JS is unavailable.
@app.get("/league={league}", response_class=HTMLResponse)
@app.get("/dashboard", response_class=HTMLResponse)
def dashboard(request: Request, league: str = DEFAULT_LEAGUE):
    d = league_data(league)
    return tpl.TemplateResponse(request, "index.html", {
        "tabs": TABS, "league": league, "asset_v": asset_v(),
        "seasons": list(reversed(d["names"])), "season": d["names"][-1],
        "league_name": d["seasons"][d["names"][-1]].name,
    })


@app.get("/load", response_class=HTMLResponse)
def load(request: Request, league: str = DEFAULT_LEAGUE, season: str | None = None,
         theme: str = "light"):
    """Load a league (or a season of it): overview panel + a refreshed shell.

    A typo'd or private league id is a normal thing for a user to do, so it
    answers with a message in the panel rather than a 500 -- the previous league
    stays on screen and can be typed back.
    """
    try:
        d, s, key = pick(league, season)
    except Exception:
        return HTMLResponse(
            "<p class='empty'>Couldn&rsquo;t load league <code>"
            f"{html_escape(league)}</code>. Check the id is a Sleeper league "
            "that has at least one scored week.</p>")
    ctx = {"league": league, "season": key, "scope": "title", "bust": 0,
           "theme": theme, "league_name": s.name,
           "seasons": list(reversed(d["names"])),
           "summary": summaries.summary_season(s),
           "charts": ["standings", "power_rank", "allplay", "luck"]}
    return tpl.TemplateResponse(request, "load.html", ctx)


def _week_context(s, week: str | int | None = None) -> dict:
    """Everything the current-week view needs: the selected week (defaulting to
    the current one), its KPI tiles and its scoreboard as games.

    Shared by the Weekly tab and the Season overview's lead section so the two
    can't drift -- overview always leads with the current week (week=None), while
    Weekly shows whatever week the rail selected.
    """
    last = s.last_week
    wk = last
    if week:
        try:
            wk = max(1, min(int(week), last))
        except (TypeError, ValueError):
            pass
    ws = metrics.week_stats(s, wk)
    decided = ws[ws["result"].isin(["W", "L", "T"])]
    wins = decided[decided["margin"] > 0]
    top = ws.iloc[0] if len(ws) else None
    blow = wins.loc[wins["margin"].idxmax()] if len(wins) else None
    close = wins.loc[wins["margin"].idxmin()] if len(wins) else None
    bench = (ws.loc[ws["left_on_bench"].idxmax()]
             if ws["left_on_bench"].notna().any() else None)
    return {
        "week": wk, "weeks": list(range(1, last + 1)),
        # Current-week framing: during a live season the view opens on
        # current_week and badges it live; on a finished season `live` is False.
        "current_week": s.current_week, "live": s.in_progress,
        "is_current": wk == s.current_week,
        # The scoreboard as GAMES, each drilling into both lineups.
        "wk_games": metrics.week_matchups(s, wk),
        "kpi_top": (f"{top['points']:.1f} · {top['user_name']}"
                    if top is not None else "—"),
        "kpi_blow": (f"+{blow['margin']:.1f} · {blow['user_name']}"
                     if blow is not None else "—"),
        "kpi_close": (f"+{close['margin']:.1f} · {close['user_name']}"
                      if close is not None else "—"),
        "kpi_bench": (f"{bench['left_on_bench']:.1f} · {bench['user_name']}"
                      if bench is not None else "—"),
    }


@app.get("/tab/{name}", response_class=HTMLResponse)
def tab(name: str, request: Request, league: str = DEFAULT_LEAGUE,
        season: str | None = None, refresh: int = 0, scope: str = "title",
        matchup: str | None = None, theme: str = "light",
        week: str | None = None, manager: str | None = None,
        bracket: str | None = None):
    if refresh:
        scoring.clear_stats_cache()      # a live week must not serve stale points
    try:
        # A refresh re-assembles the league from the API (fresh=True), not just
        # the scoring cache -- otherwise a live week's matchup points stay frozen
        # at whatever the 15-min season cache last held.
        d, s, key = pick(league, season, fresh=bool(refresh))
    except Exception:
        return HTMLResponse("<p class='empty'>Couldn&rsquo;t load league <code>"
                            f"{html_escape(league)}</code>.</p>")
    ctx = {"league": league, "season": key, "scope": scope, "theme": theme,
           "bust": int(time.time()) if refresh else 0,
           # Available to every tab so season-total views can flag, mid-season,
           # that their figures are through the current week (see _liveband.html).
           "live": s.in_progress, "current_week": s.current_week,
           # Manager team portraits, keyed by user_name (see _ident.html).
           "avatars": _avatar_map(s),
           # A custom / rolled-back bracket token rides on every playoff chart
           # + walk link so the whole tab reflects it (empty = committed bracket).
           "bracket": bracket or ""}

    if name == "overview":
        # Lead with the latest / in-progress week -- its metrics, scoreboard and
        # the two week-analytics charts -- then restate the season-to-date metrics
        # below. The week lead is the same computation the Weekly tab uses.
        ctx.update(_week_context(s))
        ctx["summary"] = summaries.summary_season(s)
        # The table-position race is rendered explicitly in Season-so-far (it
        # needs the week param), so table_position is NOT in this list -- the two
        # are the same bump chart and would duplicate. team_points stays: it
        # describes the season's arc, not any one week.
        # pf_pa (points for vs against) moved here from Coaching -- it measures
        # roster/scoring quality, not lineup decisions, so it fits beside the
        # other team-quality charts rather than the decision-focused Coaching tab.
        ctx["charts"] = ["standings", "power_rank", "allplay", "pf_pa", "luck",
                         "team_points", "sos", "schedule_swap"]
        return tpl.TemplateResponse(request, "tab_overview.html", ctx)
    elif name == "weekly":
        # One week, in full: its superlatives, then the scoreboard as games
        # that drill into both lineups. The season-arc charts live on Overview.
        ctx.update(_week_context(s, week))
        return tpl.TemplateResponse(request, "tab_weekly.html", ctx)
    elif name == "coaching":
        # Charts, then the decisions behind them: per-manager lineup weeks and
        # the individual bench calls that cost the most. pf_pa (points for vs
        # against) and boom_bust (scoring average vs volatility) measure roster
        # QUALITY, not lineup DECISIONS -- this tab's own hint says twice that
        # it's the latter, so those two moved to Overview and Roster respectively.
        ctx["charts"] = ["efficiency", "consistency"]
        ctx["standouts"] = metrics.coaching_standouts(s)
        ctx["coaching"] = metrics.coaching_detail(s)
        ctx["regrets"] = metrics.bench_regrets(s)
        return tpl.TemplateResponse(request, "tab_coaching.html", ctx)
    elif name == "roster":
        # Charts, then the rosters themselves: per manager and per week, each
        # row expanding into its detail.
        # boom_bust (scoring average vs volatility) moved here from Coaching --
        # it measures roster/scoring quality, not lineup decisions; it sits
        # beside position_box, which already covers positional scoring spread.
        ctx["charts"] = ["position_scoring", "roster_counts", "roster_heatmap",
                         "starter_bench", "position_box", "boom_bust"]
        ctx["standouts"] = metrics.roster_standouts(s)
        ctx["rosters"] = metrics.roster_detail(s)
        ctx["weeks"] = metrics.roster_weeks(s)
        return tpl.TemplateResponse(request, "tab_roster.html", ctx)
    elif name == "transactions":
        # Charts, then the deals themselves: trades kept whole (one row per team
        # in each) and the waiver wire ranked by what it actually returned.
        # waiver_performance is NOT in this grid -- it's a near-total subset of
        # the Waiver wire table below (same metric/sort/source, top 15 vs top
        # 30), so it renders directly above that table instead, where the
        # relationship is explicit rather than coincidental.
        ctx["charts"] = ["manager_profile", "trade_performance"]
        # One card per deal, not one row per team: the ledger's mirror-image
        # rows read as duplicates and print every player's name twice.
        ctx["standouts"] = metrics.transaction_standouts(s)
        deals = metrics.trade_deals(s)
        wl = metrics.waiver_ledger(s, top_n=None)   # full list; sliced below
        ctx["deals"] = deals
        ctx["n_deals"] = len(deals)
        ctx["waivers"] = records(wl.head(30))
        ctx["n_adds"] = len(wl)
        return tpl.TemplateResponse(request, "tab_transactions.html", ctx)
    elif name == "draft":
        # Draft board (round x slot) + value/grade charts for the selected
        # season; the header's picker is the only season control.
        ctx["seasons"] = list(reversed(d["names"]))
        # Grades (per-manager summary, general) before value (per-pick detail,
        # specific) -- matches the page's own "general -> specific" ordering,
        # which this pair previously ran backwards.
        ctx["charts"] = ["draft_grades", "draft_value"]
        db = draft.draft_board(s)
        if db.empty:
            ctx["no_draft"] = True
        else:
            db = db[db["draft_slot"].notna()].copy()
            db["draft_slot"] = db["draft_slot"].astype(int)
            slots = sorted(db["draft_slot"].unique())
            # A slot belongs to one team all draft, so the column header is that
            # manager; take the first row seen per slot.
            slot_user = (db.drop_duplicates("draft_slot")
                         .set_index("draft_slot")["user_name"].to_dict())
            rounds = []
            for rnd, g in db.groupby("round"):
                cells = {int(r["draft_slot"]): {
                    "pick_no": int(r["pick_no"]) if pd_notna(r["pick_no"]) else None,
                    "player": r["player_name"] or "—",
                    "pos": (r["position"] or "").upper(),
                    "points": round(float(r["points"]), 1),
                } for _, r in g.iterrows()}
                rounds.append({"round": int(rnd),
                               "cells": [cells.get(sl) for sl in slots]})
            ctx.update({"slots": slots,
                        "slot_user": [slot_user.get(sl) for sl in slots],
                        "rounds": rounds})
            ctx.update(draft.draft_extremes(s))
            # records() scrubs NaN so `{{ r.user_name or "—" }}` fires (NaN is
            # truthy in Jinja); a churned pickup can have a null primary manager.
            ctx["undrafted"] = records(draft.undrafted_standouts(s))
            # Headline tiles, matching every other tab's own stats-row-before-
            # charts convention -- reshapes data already computed above.
            ctx["standouts"] = draft.draft_standouts(s)
        return tpl.TemplateResponse(request, "tab_draft.html", ctx)
    elif name == "report":
        # The report rendered natively into the tab: its tables come straight from
        # report_parts, and its charts are ordinary /chart <img> so they stream in
        # with the same skeletons and follow the dashboard theme (the standalone
        # download bakes the same sections as embedded PNGs instead).
        mgr = manager or None
        if mgr and not (s.standings["user_name"] == mgr).any():
            mgr = None                      # scope doesn't exist in this season
        ctx.update(sm_report.report_parts(s, d["seasons"], d["playoffs"], mgr))
        ctx["manager"] = mgr
        ctx["managers"] = list(
            s.standings.sort_values("final_position")["user_name"])
        return tpl.TemplateResponse(request, "tab_report.html", ctx)
    elif name == "career":
        ctx["summary"] = summaries.summary_career(d["seasons"])
        ctx["charts"] = ["career", "trajectory", "head_to_head", "loyalty"]
        ctx["charts_intro"] = (
            "The league across every season on record &mdash; each chart&rsquo;s takeaway is "
            "noted beneath it. Identity follows the persistent account, so a manager who renamed "
            "themselves is still one person.")
        ctx["records"] = metrics.record_book(d["seasons"])
        # The all-time postseason lives here, on the league's cross-season tab;
        # the Playoffs tab shows only the season selected in the header.
        if d["playoffs"]:
            ctx["po_charts"] = ["playoff_stats_all", "playoff_players_all",
                                "clutch_all"]
            ctx["po_seasons"] = sorted(d["playoffs"])
            ctx["po_stats"] = records(sm.playoff_stats(d["playoffs"], "title"))
        # records() is what keeps `{% if m.avatar_url %}` honest: NaN is TRUTHY
        # in Jinja, so a missing avatar would otherwise render src="nan".
        ctx["managers"] = records(sm.league_accounts(d["seasons"]))
    elif name == "playoffs":
        # No season rail here: the header's season picker is the one control that
        # chooses the season, and a second in-tab switcher let the postseason
        # show 2022-2024 data while the rest of the page was on 2025.
        ctx["seasons"] = list(reversed(d["names"]))
        # A custom / rolled-back bracket (token) takes precedence over the
        # committed one; `custom` tells the template which source is live.
        pov = _bracket_from_token(bracket)
        p = pov or d["playoffs"].get(key)
        ctx["custom_bracket"] = pov is not None
        ctx["has_committed"] = d["playoffs"].get(key) is not None
        if p is None:
            ctx["missing"] = key
            return tpl.TemplateResponse(request, "tab_playoffs.html", ctx)
        r = p.results
        played = r[r["result"].isin(["W", "L", "T"])]
        top = played.loc[played["points"].idxmax()] if len(played) else None
        blow = played.loc[played["margin"].idxmax()] if len(played) else None
        # Closest game: smallest winning margin, so read it off the winners --
        # every game appears twice, once with the margin negated.
        _won = played[played["margin"] > 0]
        close = _won.loc[_won["margin"].idxmin()] if len(_won) else None
        # Best postseason PPG needs a sample: a team that played once and lost
        # otherwise "leads" on a single number, ahead of teams who played three
        # times. Prefer multi-game runs, fall back only if nobody has one.
        _sm = sm.playoff_summary(p)
        _sm = _sm[_sm["games"] > 0]
        _multi = _sm[_sm["games"] > 1]
        _pool = _multi if len(_multi) else _sm
        ppg_hi = _pool.loc[_pool["ppg"].idxmax()] if len(_pool) else None

        # The whole postseason as one round-grouped game log (each game expands to
        # both submitted lineups) -- this single drilldown replaces the old bracket
        # walk, the per-matchup chart and the separate week table. Toilet bowl is
        # computed once and folded into the log as its own group.
        _toilet = sm.toilet_bowl(s, p)
        # The run table reads as a finish order: Champion, then Runner-up, then
        # eliminations from the DEEPEST round outward (lost in the Final before
        # lost in Round 1), points breaking ties. playoff_summary sorts by
        # wins/points; re-key it here by outcome using the config's own round
        # order so "how far did they get" drives the order, not raw win count.
        _round_ix = {rd.get("name"): i
                     for i, rd in enumerate(p.config.get("rounds", []))}

        def _outcome_key(row):
            o = row.get("outcome") or ""
            pts = row.get("points") or 0
            if o == "Champion":
                return (0, 0, -pts)
            if o == "Runner-up":
                return (1, 0, -pts)
            if o.startswith("Lost in "):
                # Deeper round (higher index) ranks earlier -> negate the index.
                return (2, -_round_ix.get(o[len("Lost in "):], -1), -pts)
            return (3, 0, -pts)   # "Still alive" / "—" trail the decided runs

        _summary = records(sm.playoff_summary(p))
        _summary.sort(key=_outcome_key)
        # One "Postseason results" board, champion -> last place: the outcome-
        # ordered bracket teams, then the teams that missed the bracket beneath
        # them (worst regular-season finish, but the wooden-spoon holder forced to
        # the very bottom). A missed team's G/W/L/PPG/High/Low/Margin come from
        # its OWN toilet-bowl games (toilet_bowl's po_* fields) -- its real
        # postseason record -- rather than being discarded as "—"; "Seed" stays
        # blank since bracket seeding never applied to it.
        _last_nm = _toilet.get("last")
        _missed = sorted(_toilet.get("teams", []),
                         key=lambda t: (t["user_name"] == _last_nm,
                                        t.get("final_position", 0)))
        _results = [{**r, "in_bracket": True, "is_last": False, "sep_before": False}
                    for r in _summary]
        for i, t in enumerate(_missed):
            is_last = t["user_name"] == _last_nm
            if is_last and _toilet.get("basis") == "game":
                # An actual toilet-bowl game decided it -- crown it (ironically)
                # rather than just labelling the team "missed the bracket".
                outcome = "Toilet bowl champion"
            elif is_last:
                # No decisive game (nobody missed the bracket, or too few did
                # to play one) -- the worst regular-season finish stands in, so
                # say so rather than implying a game that never happened.
                outcome = "Missed the bracket (worst finish)"
            else:
                outcome = "Missed the bracket"
            _results.append({
                "team": t["user_name"], "seed": None,
                "games": t.get("po_games"),
                "wins": t.get("po_wins"), "losses": t.get("po_losses"),
                "ppg": t.get("po_ppg"), "high": t.get("po_high"),
                "low": t.get("po_low"), "avg_margin": t.get("po_avg_margin"),
                "outcome": outcome, "in_bracket": False, "is_last": is_last,
                # Marks the boundary so the template can draw one divider row
                # between the bracket teams and the missed-bracket teams.
                "sep_before": i == 0})
        for i, row in enumerate(_results):
            row["finish"] = i + 1
        ctx.update({
            "playoff": p,
            "champion": p.champion or "undecided",
            "games": played["matchup_id"].nunique(),
            "top": (f"{top['points']:.1f} · {top['team']}" if top is not None else "—"),
            "blow": (f"+{blow['margin']:.1f} · {blow['team']}" if blow is not None else "—"),
            "close": (f"{close['margin']:.1f} · {close['team']}"
                      if close is not None else "—"),
            "po_ppg": (f"{ppg_hi['ppg']:.1f} · {ppg_hi['team']}"
                       if ppg_hi is not None else "—"),
            "po_ppg_sub": (f"over {int(ppg_hi['games'])} games"
                           if ppg_hi is not None else ""),
            # Weeks 1..reg_weeks is the regular season; the run table cites it so
            # the seeding column can be told apart from the Overview W-L.
            "reg_weeks": s.reg_weeks,
            "log": sm.game_log(s, p, toilet=_toilet),
            # One combined finish board (bracket teams + missed teams), champion
            # to last place; see _results above.
            "results": _results,
            "toilet": _toilet,
            # No consolation games means the scope selector has nothing to
            # include or exclude -- offering it would be a dead control.
            "has_conso": bool((r.get("bracket") == "consolation").any())
            if "bracket" in r else False,
            "rules": _grouped_rules(p.config.get("scoring_settings", {})),
            "n_rules": len(p.config.get("scoring_settings", {})),
        })
        return tpl.TemplateResponse(request, "tab_playoffs.html", ctx)
    else:
        return HTMLResponse("<p class='empty'>Unknown tab.</p>", status_code=404)

    return tpl.TemplateResponse(request, "tab_charts.html", ctx)


def _report_html(d, s, key, manager: str | None = None) -> str:
    """Generate the season report and return its HTML (drawn on demand)."""
    import os
    import tempfile
    tmp = tempfile.NamedTemporaryFile(suffix=".html", delete=False)
    tmp.close()
    try:
        # The report bakes its charts as PNGs, so they can't adapt to the
        # viewer's theme after the fact -- render them light (the report's own
        # historical look). The lock + explicit theme keep a prior dark chart
        # request from leaving the global palette dark under us.
        with _render_lock:
            plots.set_chart_theme("light")
            sm.season_report(s, tmp.name, seasons=d["seasons"], playoffs=d["playoffs"],
                             manager=manager)
        with open(tmp.name, encoding="utf-8") as fh:
            return fh.read()
    finally:
        os.unlink(tmp.name)


def _report_loader(league: str, season: str | None,
                   manager: str | None = None) -> HTMLResponse:
    """A fast, styled 'building…' page that then navigates to the real render.

    The report draws ~19 charts and takes a few seconds, which otherwise shows
    as a blank tab. This returns immediately with a spinner and redirects to
    `render=1`; the browser keeps the spinner on screen until that response
    arrives, so the wait is covered instead of blank. Theme-aware so it matches
    whichever mode the viewer opened it in.
    """
    from urllib.parse import quote
    q = f"league={quote(league)}&render=1"
    if season:
        q += f"&season={quote(season)}"
    if manager:
        q += f"&manager={quote(manager)}"
    return HTMLResponse(f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Building season report…</title>
<style>
  :root {{ --bg:#f6f7f5; --ink:#1d2321; --faint:#8b938f; --turf:#2f7d4f; --line:#e2e6e3; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg:#121614; --ink:#e6ebe8; --faint:#6b7570; --turf:#5fbf85; --line:#28302c; }} }}
  html,body {{ height:100%; margin:0; }}
  body {{ display:grid; place-items:center; background:var(--bg); color:var(--ink);
    font-family:ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif; }}
  .box {{ text-align:center; }}
  .ring {{ width:42px; height:42px; margin:0 auto 18px; border-radius:50%;
    border:3px solid var(--line); border-top-color:var(--turf);
    animation:spin .8s linear infinite; }}
  @keyframes spin {{ to {{ transform:rotate(360deg); }} }}
  @media (prefers-reduced-motion:reduce) {{ .ring {{ animation-duration:2s; }} }}
  h1 {{ font-size:16px; font-weight:600; margin:0 0 4px; }}
  p {{ color:var(--faint); font-size:13px; margin:0; }}
</style></head><body>
  <div class="box">
    <div class="ring" role="status" aria-label="Building report"></div>
    <h1>Building your season report…</h1>
    <p>Drawing ~19 charts — this takes a few seconds.</p>
  </div>
  <script>location.replace("/report?{q}");</script>
</body></html>""")


@app.get("/report")
def report(league: str = DEFAULT_LEAGUE, season: str | None = None,
           download: int = 0, render: int = 0, manager: str | None = None):
    """The season report, displayed inline as a page by default.

    The primary action is to *show* the report; `download=1` returns the same
    self-contained file as an attachment instead. `manager` scopes the report to
    one team. Rendered on demand (it draws ~19 charts), so the first hit returns
    a loader (`render=0`) that navigates to the real render, keeping a spinner on
    screen during the wait.
    """
    import html as _html
    from urllib.parse import quote
    manager = manager or None
    if not download and not render:
        return _report_loader(league, season, manager)
    d, s, key = pick(league, season)
    # A manager the current season doesn't have (e.g. after switching season)
    # falls back to the whole-league report rather than erroring.
    if manager and not (s.standings["user_name"] == manager).any():
        manager = None
    doc = _report_html(d, s, key, manager)
    base = f"/report?league={quote(league)}&season={quote(key)}"
    if download:
        who = f"_{manager}" if manager else ""
        fname = f"{s.name}_{key}{who}_report.html".replace(" ", "_")
        return Response(doc, media_type="text/html", headers={
            "Content-Disposition": f'attachment; filename="{fname}"'})
    # Inline view: a sticky manager-scope tab strip across the top (matching the
    # app's own tab/rail pattern), plus a Download button, styled with the
    # report's own tokens so it adapts to light/dark. Download links back to
    # download=1, which regenerates the pristine file, so this bar never ends up
    # in the saved copy.
    dl = base + (f"&manager={quote(manager)}" if manager else "") + "&download=1"

    def _tab(href, label, active):
        return f'<a href="{href}" class="mtab{" on" if active else ""}">{label}</a>'

    tabs = [_tab(base, "Whole league", manager is None)]
    for nm in s.standings.sort_values("final_position")["user_name"]:
        tabs.append(_tab(f"{base}&manager={quote(str(nm))}",
                         _html.escape(str(nm)), manager == nm))
    bar = (
        "<style>"
        ".mbar{position:sticky;top:0;z-index:99999;display:flex;align-items:center;"
        "gap:10px;background:var(--card);border-bottom:1px solid var(--line);"
        "padding:8px 14px;font-family:system-ui,-apple-system,sans-serif;"
        "box-shadow:0 1px 10px rgba(0,0,0,.07)}"
        ".mbar .lbl{font-size:11px;font-weight:700;text-transform:uppercase;"
        "letter-spacing:.06em;color:var(--faint)}"
        ".mtabs{display:flex;gap:4px;overflow-x:auto;flex:1;scrollbar-width:thin}"
        ".mtab{white-space:nowrap;text-decoration:none;color:var(--muted);"
        "font-size:13px;font-weight:600;padding:7px 12px;border-radius:8px;"
        "border:1px solid transparent}"
        ".mtab:hover{color:var(--ink);background:color-mix(in srgb,var(--ink) 6%,transparent)}"
        ".mtab.on{color:#fff;background:var(--accent);border-color:var(--accent)}"
        ".mdl{white-space:nowrap;display:inline-flex;align-items:center;gap:6px;"
        "background:var(--accent);color:#fff;text-decoration:none;font-weight:600;"
        "font-size:13px;padding:8px 14px;border-radius:9px}"
        "</style>"
        '<nav class="mbar"><span class="lbl">Report</span>'
        f'<div class="mtabs">{"".join(tabs)}</div>'
        f'<a class="mdl" href="{dl}">&#8595; Download</a></nav>')
    # Inject at the top of the flow so `position:sticky` anchors to the viewport.
    return HTMLResponse(doc.replace('<div class="wrap">', bar + '<div class="wrap">', 1))


# --- custom playoff brackets ----------------------------------------------
# Stateless: the server generates/validates/scores brackets on demand and the
# client keeps the config (localStorage + download). "Roll back to Sleeper
# default" = fetch source=sleeper here and apply it; "reset to committed" = the
# client drops its token and the tab falls back to the committed config.
@app.get("/playoffs/default")
def playoffs_default(league: str = DEFAULT_LEAGUE, season: str | None = None,
                     source: str = "sleeper"):
    """A bracket config as JSON: the Sleeper-native bracket (the default a user
    rolls back to) or the committed config for this season -- used to seed the
    editor, to roll back, and as the download payload."""
    d, s, key = pick(league, season)
    if source == "committed":
        p = d["playoffs"].get(key)
        if p is None:
            return JSONResponse({"error": f"no committed bracket for {key}"}, status_code=404)
        return p.config
    try:
        return sm.sleeper_bracket(league, key)
    except Exception as e:
        return JSONResponse({"error": f"could not build the Sleeper bracket: {e}"},
                            status_code=502)


@app.get("/playoffs/scaffold")
def playoffs_scaffold(league: str = DEFAULT_LEAGUE, season: str | None = None,
                      weeks: str = "", teams: int = 8):
    """A seeded single-elim skeleton over a week range, starters pre-filled from
    Sleeper -- an editable baseline, not applied until the user inserts it."""
    d, s, key = pick(league, season)
    wk = [int(w) for w in weeks.replace(" ", "").split(",") if w] or None
    try:
        return sm.scaffold_bracket(league, key, wk, teams)
    except Exception as e:
        return JSONResponse({"error": f"could not scaffold: {e}"}, status_code=502)


@app.post("/playoffs/validate")
async def playoffs_validate(request: Request, league: str = DEFAULT_LEAGUE):
    try:
        cfg = await request.json()
    except Exception:
        return JSONResponse({"errors": ["body is not valid JSON"], "warnings": []},
                            status_code=400)
    return sm.validate_config(cfg, league_id=league)


# --- data for the visual bracket builder ----------------------------------
@app.get("/playoffs/seeds")
def playoffs_seeds(league: str = DEFAULT_LEAGUE, season: str | None = None):
    """Managers in regular-season standings order (name + avatar) -- the seed
    pool the builder's team dropdowns are populated from."""
    d, s, key = pick(league, season)
    order = list(s.standings.sort_values("final_position")["user_name"])
    av = _avatar_map(s)
    return [{"seed": i + 1, "name": n, "avatar": av.get(n)}
            for i, n in enumerate(order)]


@app.get("/playoffs/roster")
def playoffs_roster(league: str = DEFAULT_LEAGUE, season: str | None = None,
                    team: str = "", week: int = 0):
    """A manager's rostered players for a week + the league's empty starting
    slots, so lineups are picked from real players (never typed ids). Reads the
    Sleeper matchup directly, so it works for custom playoff weeks beyond the
    season object's regular-season cap."""
    from sleepermetrics.season import slot_template
    d, s, key = pick(league, season)
    row = s.user_map[s.user_map["user_name"] == team]
    slots = slot_template(getattr(s, "slots", {}) or {})
    if not len(row) or not week:
        return {"team": team, "week": week, "slots": slots, "players": [], "prefill": []}
    rid = int(row["roster_id"].iloc[0])
    pinfo = sm.players()
    pos = pinfo.set_index("player_id")["position"]
    name = pinfo.set_index("player_id")["player_name"]
    ids, prefill = [], []
    try:
        for m in sm.sleeper_api(f"/league/{s.league_id}/matchups/{int(week)}"):
            if m.get("roster_id") == rid:
                ids = [str(p) for p in (m.get("players") or [])]
                prefill = [str(p) for p in (m.get("starters") or []) if p and p != "0"]
                break
    except Exception:
        pass

    def _p(pid):
        return {"id": pid, "name": name.get(pid, pid), "position": pos.get(pid, "")}
    return {"team": team, "week": week, "slots": slots,
            "players": [_p(p) for p in ids], "prefill": prefill}


@app.post("/playoffs/custom")
async def playoffs_custom(request: Request, league: str = DEFAULT_LEAGUE):
    """Validate + score a user bracket and return a token the tab/charts
    reference via ?bracket=<token>. Nothing is persisted server-side."""
    try:
        cfg = await request.json()
    except Exception:
        return JSONResponse({"ok": False, "errors": ["body is not valid JSON"],
                             "warnings": []}, status_code=400)
    res = sm.validate_config(cfg, league_id=league)
    if res["errors"]:
        return {"ok": False, "errors": res["errors"], "warnings": res["warnings"]}
    try:
        tok, p = _cache_bracket(cfg)
    except Exception as e:
        return {"ok": False, "errors": [f"could not score bracket: {e}"],
                "warnings": res["warnings"]}
    games = int(p.results["matchup_id"].nunique()) if len(p.results) else 0
    return {"ok": True, "token": tok, "errors": [], "warnings": res["warnings"],
            "champion": p.champion, "name": p.name, "games": games}


@app.get("/health")
def health():
    return {"ok": True, "league": DEFAULT_LEAGUE}
