"""FastAPI + HTMX dashboard — the Python instance's web app.

Mirrors the R Shiny dashboard (sl_dashboard) tab for tab. Charts are the very
same matplotlib figures the package already renders, streamed as PNG, so the
R<->Python chart mirror and the parity harness keep protecting them -- the web
layer adds no new plotting code.

    python launch.py python dashboard [--port 8000]
    uvicorn webapp.app:app --reload      # from python/
"""
from __future__ import annotations

import io
import os
import threading
import time
from html import escape as html_escape
from pathlib import Path

import matplotlib
from fastapi import FastAPI, Query, Request
from fastapi.responses import HTMLResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

matplotlib.use("Agg")

import sleepermetrics as sm  # noqa: E402
from sleepermetrics import draft, metrics, plots, scoring, summaries  # noqa: E402

BASE = Path(__file__).resolve().parent
ROOT = BASE.parent.parent                       # repo root
PLAYOFF_DIR = os.environ.get("SLEEPERMETRICS_PLAYOFFS", str(ROOT / "playoffs"))
DEFAULT_LEAGUE = os.environ.get("SLEEPERMETRICS_LEAGUE", "1252770181306929152")
TTL = int(os.environ.get("SLEEPERMETRICS_TTL", "900"))   # cache seasons 15 min

app = FastAPI(title="Sleeper League Analytics")
app.mount("/static", StaticFiles(directory=BASE / "static"), name="static")
tpl = Jinja2Templates(directory=str(BASE / "templates"))


def _md(text: str):
    """Render the summaries' small markdown subset (###, -, **bold**, `code`).

    The summaries are generated by us and use exactly these four constructs, so a
    full markdown dependency would be dead weight. The input is html-escaped
    first, so marking the result safe only trusts the tags this function emits --
    never the data.
    """
    import html
    import re

    from markupsafe import Markup
    out, ul = [], False
    for line in html.escape(text or "").splitlines():
        line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
        line = re.sub(r"`(.+?)`", r"<code>\1</code>", line)
        if line.startswith("### "):
            if ul:
                out.append("</ul>")
                ul = False
            out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("- "):
            if not ul:
                out.append("<ul>")
                ul = True
            out.append(f"<li>{line[2:]}</li>")
        elif line.strip():
            if ul:
                out.append("</ul>")
                ul = False
            out.append(f"<p>{line}</p>")
    if ul:
        out.append("</ul>")
    return Markup("\n".join(out))


tpl.env.filters["md"] = _md


def _playoff_games(p) -> list[dict]:
    """Every game in the bracket, in the order it was played.

    The raw matchup ids sort alphabetically, which is not bracket order once a
    bracket has more than 9 games (R1M10 lands before R1M2) and says nothing
    about rounds. Walk the results frame instead -- the engine emits it round by
    round -- and describe each game well enough to navigate by.
    """
    games, seen = [], set()
    for mid in p.results["matchup_id"]:
        if mid in seen:
            continue
        seen.add(mid)
        rows = p.results[p.results["matchup_id"] == mid]
        sides = [{"team": r["team"], "points": r["points"], "result": r["result"]}
                 for _, r in rows.iterrows() if pd_notna(r["team"])]
        played = [x for x in sides if x["result"] in ("W", "L", "T")]
        winner = next((x["team"] for x in sides if x["result"] == "W"), None)
        first = rows.iloc[0]
        games.append({
            "id": mid,
            "round": first.get("round") or first.get("round_id"),
            "weeks": first.get("weeks"),
            "bracket": first.get("bracket"),
            "sides": sides,
            "winner": winner,
            "played": bool(played),
            # A bye has one side; an undecided game has teams but no result yet.
            "label": " vs ".join(x["team"] for x in sides) if sides else "TBD",
        })
    return games


def pd_notna(v) -> bool:
    import pandas as pd
    return bool(pd.notna(v))


def _grouped_rules(settings: dict) -> list[tuple[str, list[dict]]]:
    """The point-calculation chart as [(group, [rule, ...])], in plain English.

    Sleeper keys the chart by stat code (`bonus_rec_te`); a manager reading why
    they lost should not have to know what that means. statnames does the
    translating -- shared with the R dashboard and parity-checked against it.
    """
    d = sm.scoring_readable(settings)
    return [(g, rows.to_dict("records")) for g, rows in d.groupby("group", sort=False)]

TABS = [
    ("overview", "Season overview"), ("weekly", "Weekly trends"),
    ("coaching", "Coaching & scoring"), ("roster", "Roster & positions"),
    ("transactions", "Transactions"), ("draft", "Draft"),
    ("playoffs", "Playoffs"), ("career", "Career"),
]

# --- cache ----------------------------------------------------------------
# Assembling a league is many API calls, so hold it briefly rather than rebuild
# it on every tab switch. Charts are cheap to redraw from the cached frames.
_cache: dict = {}


def league_data(league_id: str, fresh: bool = False) -> dict:
    hit = _cache.get(league_id)
    if hit and not fresh and time.time() - hit["at"] < TTL:
        return hit
    seasons = sm.apply_playoffs(sm.seasons(league_id), PLAYOFF_DIR)
    # Only this league's brackets -- a stored 2025.json belongs to a league, not
    # to the number 2025, so another league must not inherit DDBM's playoffs.
    playoffs = sm.load_playoffs(
        PLAYOFF_DIR, league_ids=[s.league_id for s in seasons.values()])
    d = {"at": time.time(), "seasons": seasons, "playoffs": playoffs,
         "names": list(seasons)}
    _cache[league_id] = d
    return d


def pick(league_id: str, season: str | None, fresh: bool = False):
    d = league_data(league_id, fresh)
    key = season if season in d["seasons"] else d["names"][-1]
    return d, d["seasons"][key], key


# matplotlib's pyplot state is global and not thread-safe, and the chart theme
# is a module-level token that a request flips before drawing -- so every render
# path holds this lock, or two concurrent requests could draw on each other's
# theme (a dark chart saved with a light facecolor, say).
_render_lock = threading.Lock()


def png(fig) -> Response:
    buf = io.BytesIO()
    # Match the saved facecolor to the active theme so a dark chart isn't matted
    # onto a white rectangle. plots.T is already the theme set under the lock.
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight",
                facecolor=plots.T["bg"])
    matplotlib.pyplot.close(fig)
    # Cacheable per (url incl. theme + bust): the browser reuses charts across
    # tab visits instead of re-fetching every switch. `bust` changes on a live
    # re-score, so a refreshed week is never served stale.
    return Response(buf.getvalue(), media_type="image/png",
                    headers={"Cache-Control": "private, max-age=120"})


# --- chart registry -------------------------------------------------------
# name -> (scope, fn). Season charts take a Season; career/playoff charts take
# the whole league. Everything comes straight from plots.py.
SEASON_CHARTS = {
    "standings": plots.plot_standings, "luck": plots.plot_luck,
    "efficiency": plots.plot_efficiency, "consistency": plots.plot_consistency,
    "pf_pa": plots.plot_pf_pa, "table_position": plots.plot_table_position,
    "team_points": plots.plot_team_points,
    "allplay": plots.plot_allplay, "power_rank": plots.plot_power_rank,
    "manager_profile": plots.plot_manager_profile,
    "position_scoring": plots.plot_position_scoring,
    "roster_heatmap": plots.plot_roster_heatmap,
    "starter_bench": plots.plot_starter_bench,
    "position_box": plots.plot_position_box,
    "roster_counts": plots.plot_roster_counts,
    "trade_performance": plots.plot_trade_performance,
    "waiver_performance": plots.plot_waiver_performance,
    "boom_bust": plots.plot_boom_bust, "sos": plots.plot_sos,
    "schedule_swap": plots.plot_schedule_swap,
    "draft_value": plots.plot_draft_value, "draft_grades": plots.plot_draft_grades,
}


@app.get("/chart/{name}")
def chart(name: str, league: str = DEFAULT_LEAGUE, season: str | None = None,
          matchup: str | None = None, scope: str = "title",
          theme: str = "light", _: str | None = None):
    d, s, key = pick(league, season)
    # Build + save under the lock, with the requested theme active, so the
    # structural palette and the saved facecolor can't be crossed by a
    # concurrent request drawing in the other theme.
    with _render_lock:
        plots.set_chart_theme(theme)
        if name in SEASON_CHARTS:
            return png(SEASON_CHARTS[name](s))
        if name == "career":
            return png(plots.plot_career(d["seasons"]))
        if name == "trajectory":
            return png(plots.plot_trajectory(d["seasons"]))
        if name == "loyalty":
            return png(plots.plot_loyalty(d["seasons"]))
        if name == "head_to_head":
            return png(plots.plot_head_to_head(d["seasons"]))
        if name == "playoff_stats":
            return png(plots.plot_playoff_stats(d["playoffs"], scope))
        if name == "playoff_players":
            return png(plots.plot_playoff_players(d["playoffs"], scope=scope))
        if name == "clutch":
            return png(plots.plot_clutch(d["seasons"], d["playoffs"], scope))
        if name == "bracket":
            p = d["playoffs"].get(key)
            return png(plots.plot_playoff_bracket(p))
        if name == "playoff_matchup":
            p = d["playoffs"].get(key)
            mid = matchup or p.config.get("final")
            return png(plots.plot_playoff_matchup(p, mid))
    return Response(status_code=404)


# --- pages ----------------------------------------------------------------
@app.get("/", response_class=HTMLResponse)
def index(request: Request, league: str = DEFAULT_LEAGUE):
    d = league_data(league)
    return tpl.TemplateResponse(request, "index.html", {
        "tabs": TABS, "league": league,
        "seasons": list(reversed(d["names"])), "season": d["names"][-1],
        "league_name": d["seasons"][d["names"][-1]].name,
    })


@app.get("/load", response_class=HTMLResponse)
def load(request: Request, league: str = DEFAULT_LEAGUE, season: str | None = None,
         theme: str = "light"):
    """Load a league (or a season of it): overview panel + a refreshed shell.

    A typo'd or private league id is a normal thing for a user to do, so it
    answers with a message in the panel rather than a 500 -- the previous league
    stays on screen and can be typed back.
    """
    try:
        d, s, key = pick(league, season)
    except Exception:
        return HTMLResponse(
            "<p class='empty'>Couldn&rsquo;t load league <code>"
            f"{html_escape(league)}</code>. Check the id is a Sleeper league "
            "that has at least one scored week.</p>")
    ctx = {"league": league, "season": key, "scope": "title", "bust": 0,
           "theme": theme, "league_name": s.name,
           "seasons": list(reversed(d["names"])),
           "summary": summaries.summary_season(s),
           "charts": ["standings", "power_rank", "allplay", "luck"]}
    return tpl.TemplateResponse(request, "load.html", ctx)


@app.get("/tab/{name}", response_class=HTMLResponse)
def tab(name: str, request: Request, league: str = DEFAULT_LEAGUE,
        season: str | None = None, refresh: int = 0, scope: str = "title",
        matchup: str | None = None, theme: str = "light",
        week: str | None = None):
    if refresh:
        scoring.clear_stats_cache()      # a live week must not serve stale points
    try:
        d, s, key = pick(league, season)
    except Exception:
        return HTMLResponse("<p class='empty'>Couldn&rsquo;t load league <code>"
                            f"{html_escape(league)}</code>.</p>")
    ctx = {"league": league, "season": key, "scope": scope, "theme": theme,
           "bust": int(time.time()) if refresh else 0}

    if name == "overview":
        ctx["summary"] = summaries.summary_season(s)
        ctx["charts"] = ["standings", "power_rank", "allplay", "luck",
                         "sos", "schedule_swap"]
    elif name == "weekly":
        # Season-long trend charts, plus a drill-down into a single week: its
        # scoreboard and the week's superlatives, from the week_stats metric.
        last = s.last_week
        wk = last
        if week:
            try:
                wk = max(1, min(int(week), last))
            except ValueError:
                pass
        ws = sm.metrics.week_stats(s, wk)
        decided = ws[ws["result"].isin(["W", "L", "T"])]
        wins = decided[decided["margin"] > 0]

        def _one(row, val):
            return f"{val} · {row['user_name']}" if row is not None else "—"

        top = ws.iloc[0] if len(ws) else None
        blow = wins.loc[wins["margin"].idxmax()] if len(wins) else None
        close = wins.loc[wins["margin"].idxmin()] if len(wins) else None
        bench = (ws.loc[ws["left_on_bench"].idxmax()]
                 if ws["left_on_bench"].notna().any() else None)
        ctx.update({
            "charts": ["table_position", "team_points"],
            "week": wk, "weeks": list(range(1, last + 1)),
            "wk_rows": ws.to_dict("records"),
            "kpi_top": _one(top, f"{top['points']:.1f}") if top is not None else "—",
            "kpi_blow": (f"+{blow['margin']:.1f} · {blow['user_name']}"
                         if blow is not None else "—"),
            "kpi_close": (f"+{close['margin']:.1f} · {close['user_name']}"
                          if close is not None else "—"),
            "kpi_bench": (f"{bench['left_on_bench']:.1f} · {bench['user_name']}"
                          if bench is not None else "—"),
        })
        return tpl.TemplateResponse(request, "tab_weekly.html", ctx)
    elif name == "coaching":
        ctx["charts"] = ["efficiency", "consistency", "pf_pa", "boom_bust"]
    elif name == "roster":
        ctx["charts"] = ["position_scoring", "roster_counts", "roster_heatmap",
                         "starter_bench", "position_box"]
    elif name == "transactions":
        ctx["charts"] = ["manager_profile", "trade_performance", "waiver_performance"]
    elif name == "draft":
        # Historical draft board (round x slot) + value/grade charts. A season
        # rail lets past drafts be walked without leaving the tab.
        ctx["seasons"] = list(reversed(d["names"]))
        ctx["draft_seasons"] = list(reversed(d["names"]))
        ctx["charts"] = ["draft_value", "draft_grades"]
        db = draft.draft_board(s)
        if db.empty:
            ctx["no_draft"] = True
        else:
            db = db[db["draft_slot"].notna()].copy()
            db["draft_slot"] = db["draft_slot"].astype(int)
            slots = sorted(db["draft_slot"].unique())
            # A slot belongs to one team all draft, so the column header is that
            # manager; take the first row seen per slot.
            slot_user = (db.drop_duplicates("draft_slot")
                         .set_index("draft_slot")["user_name"].to_dict())
            rounds = []
            for rnd, g in db.groupby("round"):
                cells = {int(r["draft_slot"]): {
                    "pick_no": int(r["pick_no"]) if pd_notna(r["pick_no"]) else None,
                    "player": r["player_name"] or "—",
                    "pos": (r["position"] or "").upper(),
                    "points": round(float(r["points"]), 1),
                } for _, r in g.iterrows()}
                rounds.append({"round": int(rnd),
                               "cells": [cells.get(sl) for sl in slots]})
            ctx.update({"slots": slots,
                        "slot_user": [slot_user.get(sl) for sl in slots],
                        "rounds": rounds})
        return tpl.TemplateResponse(request, "tab_draft.html", ctx)
    elif name == "career":
        ctx["summary"] = summaries.summary_career(d["seasons"])
        ctx["charts"] = ["career", "trajectory", "head_to_head", "loyalty"]
        ctx["records"] = metrics.record_book(d["seasons"])
        mg = sm.league_accounts(d["seasons"])
        # NaN is TRUTHY in Jinja, so a missing avatar would sail through
        # `{% if m.avatar_url %}` and render src="nan". Hand the template None.
        mg = mg.astype(object).where(mg.notna(), None)
        ctx["managers"] = mg.to_dict("records")
    elif name == "playoffs":
        # The season rail: every season of this league that HAS a stored bracket,
        # so the postseasons can be walked without leaving the tab.
        ctx["bracket_seasons"] = [n for n in d["names"] if n in d["playoffs"]]
        # Walking to another season from in here must also move the header's
        # season picker, or the two disagree about what is on screen.
        ctx["seasons"] = list(reversed(d["names"]))
        p = d["playoffs"].get(key)
        if p is None:
            ctx["missing"] = key
            return tpl.TemplateResponse(request, "tab_playoffs.html", ctx)
        r = p.results
        played = r[r["result"].isin(["W", "L", "T"])]
        top = played.loc[played["points"].idxmax()] if len(played) else None
        blow = played.loc[played["margin"].idxmax()] if len(played) else None

        # Walk the bracket game by game, in the order it was actually played.
        all_games = _playoff_games(p)
        walk = [g for g in all_games if g["played"]]
        ids = [g["id"] for g in walk]
        cur = matchup if matchup in ids else (p.config.get("final")
                                              if p.config.get("final") in ids
                                              else (ids[-1] if ids else None))
        i = ids.index(cur) if cur in ids else -1
        ctx.update({
            "playoff": p,
            "champion": p.champion or "undecided",
            "games": played["matchup_id"].nunique(),
            "top": (f"{top['points']:.1f} · {top['team']}" if top is not None else "—"),
            "blow": (f"+{blow['margin']:.1f} · {blow['team']}" if blow is not None else "—"),
            "walk": walk,
            "matchup": cur,
            "prev": ids[i - 1] if i > 0 else None,
            "next": ids[i + 1] if 0 <= i < len(ids) - 1 else None,
            "step": (i + 1) if i >= 0 else 0,
            "n_steps": len(ids),
            "summary": sm.playoff_summary(p).to_dict("records"),
            "stats": sm.playoff_stats(d["playoffs"], scope).to_dict("records"),
            "rules": _grouped_rules(p.config.get("scoring_settings", {})),
            "n_rules": len(p.config.get("scoring_settings", {})),
        })
        return tpl.TemplateResponse(request, "tab_playoffs.html", ctx)
    else:
        return HTMLResponse("<p class='empty'>Unknown tab.</p>", status_code=404)

    return tpl.TemplateResponse(request, "tab_charts.html", ctx)


def _report_html(d, s, key) -> str:
    """Generate the season report and return its HTML (drawn on demand)."""
    import os
    import tempfile
    tmp = tempfile.NamedTemporaryFile(suffix=".html", delete=False)
    tmp.close()
    try:
        # The report bakes its charts as PNGs, so they can't adapt to the
        # viewer's theme after the fact -- render them light (the report's own
        # historical look). The lock + explicit theme keep a prior dark chart
        # request from leaving the global palette dark under us.
        with _render_lock:
            plots.set_chart_theme("light")
            sm.season_report(s, tmp.name, seasons=d["seasons"], playoffs=d["playoffs"])
        with open(tmp.name, encoding="utf-8") as fh:
            return fh.read()
    finally:
        os.unlink(tmp.name)


def _report_loader(league: str, season: str | None) -> HTMLResponse:
    """A fast, styled 'building…' page that then navigates to the real render.

    The report draws ~19 charts and takes a few seconds, which otherwise shows
    as a blank tab. This returns immediately with a spinner and redirects to
    `render=1`; the browser keeps the spinner on screen until that response
    arrives, so the wait is covered instead of blank. Theme-aware so it matches
    whichever mode the viewer opened it in.
    """
    from urllib.parse import quote
    q = f"league={quote(league)}&render=1"
    if season:
        q += f"&season={quote(season)}"
    return HTMLResponse(f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Building season report…</title>
<style>
  :root {{ --bg:#f6f7f5; --ink:#1d2321; --faint:#8b938f; --turf:#2f7d4f; --line:#e2e6e3; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg:#121614; --ink:#e6ebe8; --faint:#6b7570; --turf:#5fbf85; --line:#28302c; }} }}
  html,body {{ height:100%; margin:0; }}
  body {{ display:grid; place-items:center; background:var(--bg); color:var(--ink);
    font-family:ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif; }}
  .box {{ text-align:center; }}
  .ring {{ width:42px; height:42px; margin:0 auto 18px; border-radius:50%;
    border:3px solid var(--line); border-top-color:var(--turf);
    animation:spin .8s linear infinite; }}
  @keyframes spin {{ to {{ transform:rotate(360deg); }} }}
  @media (prefers-reduced-motion:reduce) {{ .ring {{ animation-duration:2s; }} }}
  h1 {{ font-size:16px; font-weight:600; margin:0 0 4px; }}
  p {{ color:var(--faint); font-size:13px; margin:0; }}
</style></head><body>
  <div class="box">
    <div class="ring" role="status" aria-label="Building report"></div>
    <h1>Building your season report…</h1>
    <p>Drawing ~19 charts — this takes a few seconds.</p>
  </div>
  <script>location.replace("/report?{q}");</script>
</body></html>""")


@app.get("/report")
def report(league: str = DEFAULT_LEAGUE, season: str | None = None,
           download: int = 0, render: int = 0):
    """The season report, displayed inline as a page by default.

    The primary action is to *show* the report; `download=1` returns the same
    self-contained file as an attachment instead. Rendered on demand (it draws
    ~19 charts), so the first hit returns a loader (`render=0`) that navigates
    to the real render, keeping a spinner on screen during the wait.
    """
    from urllib.parse import quote
    if not download and not render:
        return _report_loader(league, season)
    d, s, key = pick(league, season)
    doc = _report_html(d, s, key)
    if download:
        fname = f"{s.name}_{key}_report.html".replace(" ", "_")
        return Response(doc, media_type="text/html", headers={
            "Content-Disposition": f'attachment; filename="{fname}"'})
    # Inline view: float a Download button over the report (styled with the
    # report's own --accent token so it adapts to its light/dark theme). The
    # button links back to download=1, which regenerates the pristine file --
    # the on-screen toolbar never ends up in the saved copy.
    dl = f"/report?league={quote(league)}&season={quote(key)}&download=1"
    bar = (
        '<div style="position:fixed;top:14px;right:16px;z-index:99999;'
        'font-family:system-ui,-apple-system,sans-serif">'
        f'<a href="{dl}" style="display:inline-flex;align-items:center;gap:6px;'
        'background:var(--accent);color:#fff;text-decoration:none;font-weight:600;'
        'font-size:13px;padding:8px 14px;border-radius:9px;'
        'box-shadow:0 2px 10px rgba(0,0,0,.18)">&#8595; Download</a></div>')
    return HTMLResponse(doc.replace("</body>", bar + "</body>"))


@app.get("/health")
def health():
    return {"ok": True, "league": DEFAULT_LEAGUE}
