"""FastAPI + HTMX dashboard — the Python instance's web app.

Mirrors the R Shiny dashboard (sl_dashboard) tab for tab. Charts are the very
same matplotlib figures the package already renders, streamed as PNG, so the
R<->Python chart mirror and the parity harness keep protecting them -- the web
layer adds no new plotting code.

    python launch.py python dashboard [--port 8000]
    uvicorn webapp.app:app --reload      # from python/
"""
from __future__ import annotations

import io
import os
import time
from html import escape as html_escape
from pathlib import Path

import matplotlib
from fastapi import FastAPI, Query, Request
from fastapi.responses import FileResponse, HTMLResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

matplotlib.use("Agg")

import sleepermetrics as sm  # noqa: E402
from sleepermetrics import metrics, plots, scoring, summaries  # noqa: E402

BASE = Path(__file__).resolve().parent
ROOT = BASE.parent.parent                       # repo root
PLAYOFF_DIR = os.environ.get("SLEEPERMETRICS_PLAYOFFS", str(ROOT / "playoffs"))
DEFAULT_LEAGUE = os.environ.get("SLEEPERMETRICS_LEAGUE", "1252770181306929152")
TTL = int(os.environ.get("SLEEPERMETRICS_TTL", "900"))   # cache seasons 15 min

app = FastAPI(title="Sleeper League Analytics")
app.mount("/static", StaticFiles(directory=BASE / "static"), name="static")
tpl = Jinja2Templates(directory=str(BASE / "templates"))


def _md(text: str):
    """Render the summaries' small markdown subset (###, -, **bold**, `code`).

    The summaries are generated by us and use exactly these four constructs, so a
    full markdown dependency would be dead weight. The input is html-escaped
    first, so marking the result safe only trusts the tags this function emits --
    never the data.
    """
    import html
    import re

    from markupsafe import Markup
    out, ul = [], False
    for line in html.escape(text or "").splitlines():
        line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
        line = re.sub(r"`(.+?)`", r"<code>\1</code>", line)
        if line.startswith("### "):
            if ul:
                out.append("</ul>")
                ul = False
            out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("- "):
            if not ul:
                out.append("<ul>")
                ul = True
            out.append(f"<li>{line[2:]}</li>")
        elif line.strip():
            if ul:
                out.append("</ul>")
                ul = False
            out.append(f"<p>{line}</p>")
    if ul:
        out.append("</ul>")
    return Markup("\n".join(out))


tpl.env.filters["md"] = _md


def _playoff_games(p) -> list[dict]:
    """Every game in the bracket, in the order it was played.

    The raw matchup ids sort alphabetically, which is not bracket order once a
    bracket has more than 9 games (R1M10 lands before R1M2) and says nothing
    about rounds. Walk the results frame instead -- the engine emits it round by
    round -- and describe each game well enough to navigate by.
    """
    games, seen = [], set()
    for mid in p.results["matchup_id"]:
        if mid in seen:
            continue
        seen.add(mid)
        rows = p.results[p.results["matchup_id"] == mid]
        sides = [{"team": r["team"], "points": r["points"], "result": r["result"]}
                 for _, r in rows.iterrows() if pd_notna(r["team"])]
        played = [x for x in sides if x["result"] in ("W", "L", "T")]
        winner = next((x["team"] for x in sides if x["result"] == "W"), None)
        first = rows.iloc[0]
        games.append({
            "id": mid,
            "round": first.get("round") or first.get("round_id"),
            "weeks": first.get("weeks"),
            "bracket": first.get("bracket"),
            "sides": sides,
            "winner": winner,
            "played": bool(played),
            # A bye has one side; an undecided game has teams but no result yet.
            "label": " vs ".join(x["team"] for x in sides) if sides else "TBD",
        })
    return games


def pd_notna(v) -> bool:
    import pandas as pd
    return bool(pd.notna(v))


def _grouped_rules(settings: dict) -> list[tuple[str, list[dict]]]:
    """The point-calculation chart as [(group, [rule, ...])], in plain English.

    Sleeper keys the chart by stat code (`bonus_rec_te`); a manager reading why
    they lost should not have to know what that means. statnames does the
    translating -- shared with the R dashboard and parity-checked against it.
    """
    d = sm.scoring_readable(settings)
    return [(g, rows.to_dict("records")) for g, rows in d.groupby("group", sort=False)]

TABS = [
    ("overview", "Season overview"), ("weekly", "Weekly trends"),
    ("coaching", "Coaching & scoring"), ("roster", "Roster & positions"),
    ("transactions", "Transactions"), ("playoffs", "Playoffs"),
    ("career", "Career"),
]

# --- cache ----------------------------------------------------------------
# Assembling a league is many API calls, so hold it briefly rather than rebuild
# it on every tab switch. Charts are cheap to redraw from the cached frames.
_cache: dict = {}


def league_data(league_id: str, fresh: bool = False) -> dict:
    hit = _cache.get(league_id)
    if hit and not fresh and time.time() - hit["at"] < TTL:
        return hit
    seasons = sm.apply_playoffs(sm.seasons(league_id), PLAYOFF_DIR)
    # Only this league's brackets -- a stored 2025.json belongs to a league, not
    # to the number 2025, so another league must not inherit DDBM's playoffs.
    playoffs = sm.load_playoffs(
        PLAYOFF_DIR, league_ids=[s.league_id for s in seasons.values()])
    d = {"at": time.time(), "seasons": seasons, "playoffs": playoffs,
         "names": list(seasons)}
    _cache[league_id] = d
    return d


def pick(league_id: str, season: str | None, fresh: bool = False):
    d = league_data(league_id, fresh)
    key = season if season in d["seasons"] else d["names"][-1]
    return d, d["seasons"][key], key


def png(fig) -> Response:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight", facecolor="white")
    matplotlib.pyplot.close(fig)
    return Response(buf.getvalue(), media_type="image/png",
                    headers={"Cache-Control": "no-cache"})


# --- chart registry -------------------------------------------------------
# name -> (scope, fn). Season charts take a Season; career/playoff charts take
# the whole league. Everything comes straight from plots.py.
SEASON_CHARTS = {
    "standings": plots.plot_standings, "luck": plots.plot_luck,
    "efficiency": plots.plot_efficiency, "consistency": plots.plot_consistency,
    "pf_pa": plots.plot_pf_pa, "table_position": plots.plot_table_position,
    "team_points": plots.plot_team_points,
    "allplay": plots.plot_allplay, "power_rank": plots.plot_power_rank,
    "manager_profile": plots.plot_manager_profile,
    "position_scoring": plots.plot_position_scoring,
    "roster_heatmap": plots.plot_roster_heatmap,
    "starter_bench": plots.plot_starter_bench,
    "position_box": plots.plot_position_box,
    "roster_counts": plots.plot_roster_counts,
    "trade_performance": plots.plot_trade_performance,
    "waiver_performance": plots.plot_waiver_performance,
}


@app.get("/chart/{name}")
def chart(name: str, league: str = DEFAULT_LEAGUE, season: str | None = None,
          matchup: str | None = None, scope: str = "title", _: str | None = None):
    d, s, key = pick(league, season)
    if name in SEASON_CHARTS:
        return png(SEASON_CHARTS[name](s))
    if name == "career":
        return png(plots.plot_career(d["seasons"]))
    if name == "trajectory":
        return png(plots.plot_trajectory(d["seasons"]))
    if name == "playoff_stats":
        return png(plots.plot_playoff_stats(d["playoffs"], scope))
    if name == "playoff_players":
        return png(plots.plot_playoff_players(d["playoffs"], scope=scope))
    if name == "clutch":
        return png(plots.plot_clutch(d["seasons"], d["playoffs"], scope))
    if name == "bracket":
        p = d["playoffs"].get(key)
        return png(plots.plot_playoff_bracket(p))
    if name == "playoff_matchup":
        p = d["playoffs"].get(key)
        mid = matchup or p.config.get("final")
        return png(plots.plot_playoff_matchup(p, mid))
    return Response(status_code=404)


# --- pages ----------------------------------------------------------------
@app.get("/", response_class=HTMLResponse)
def index(request: Request, league: str = DEFAULT_LEAGUE):
    d = league_data(league)
    return tpl.TemplateResponse(request, "index.html", {
        "tabs": TABS, "league": league,
        "seasons": list(reversed(d["names"])), "season": d["names"][-1],
        "league_name": d["seasons"][d["names"][-1]].name,
    })


@app.get("/load", response_class=HTMLResponse)
def load(request: Request, league: str = DEFAULT_LEAGUE, season: str | None = None):
    """Load a league (or a season of it): overview panel + a refreshed shell.

    A typo'd or private league id is a normal thing for a user to do, so it
    answers with a message in the panel rather than a 500 -- the previous league
    stays on screen and can be typed back.
    """
    try:
        d, s, key = pick(league, season)
    except Exception:
        return HTMLResponse(
            "<p class='empty'>Couldn&rsquo;t load league <code>"
            f"{html_escape(league)}</code>. Check the id is a Sleeper league "
            "that has at least one scored week.</p>")
    ctx = {"league": league, "season": key, "scope": "title", "bust": 0,
           "league_name": s.name, "seasons": list(reversed(d["names"])),
           "summary": summaries.summary_season(s),
           "charts": ["standings", "power_rank", "allplay", "luck"]}
    return tpl.TemplateResponse(request, "load.html", ctx)


@app.get("/tab/{name}", response_class=HTMLResponse)
def tab(name: str, request: Request, league: str = DEFAULT_LEAGUE,
        season: str | None = None, refresh: int = 0, scope: str = "title",
        matchup: str | None = None):
    if refresh:
        scoring.clear_stats_cache()      # a live week must not serve stale points
    try:
        d, s, key = pick(league, season)
    except Exception:
        return HTMLResponse("<p class='empty'>Couldn&rsquo;t load league <code>"
                            f"{html_escape(league)}</code>.</p>")
    ctx = {"league": league, "season": key, "scope": scope,
           "bust": int(time.time()) if refresh else 0}

    if name == "overview":
        ctx["summary"] = summaries.summary_season(s)
        ctx["charts"] = ["standings", "power_rank", "allplay", "luck"]
    elif name == "weekly":
        ctx["charts"] = ["table_position", "team_points"]
    elif name == "coaching":
        ctx["charts"] = ["efficiency", "consistency", "pf_pa"]
    elif name == "roster":
        ctx["charts"] = ["position_scoring", "roster_counts", "roster_heatmap",
                         "starter_bench", "position_box"]
    elif name == "transactions":
        ctx["charts"] = ["manager_profile", "trade_performance", "waiver_performance"]
    elif name == "career":
        ctx["summary"] = summaries.summary_career(d["seasons"])
        ctx["charts"] = ["career", "trajectory"]
        mg = sm.league_accounts(d["seasons"])
        # NaN is TRUTHY in Jinja, so a missing avatar would sail through
        # `{% if m.avatar_url %}` and render src="nan". Hand the template None.
        mg = mg.astype(object).where(mg.notna(), None)
        ctx["managers"] = mg.to_dict("records")
    elif name == "playoffs":
        # The season rail: every season of this league that HAS a stored bracket,
        # so the postseasons can be walked without leaving the tab.
        ctx["bracket_seasons"] = [n for n in d["names"] if n in d["playoffs"]]
        # Walking to another season from in here must also move the header's
        # season picker, or the two disagree about what is on screen.
        ctx["seasons"] = list(reversed(d["names"]))
        p = d["playoffs"].get(key)
        if p is None:
            ctx["missing"] = key
            return tpl.TemplateResponse(request, "tab_playoffs.html", ctx)
        r = p.results
        played = r[r["result"].isin(["W", "L", "T"])]
        top = played.loc[played["points"].idxmax()] if len(played) else None
        blow = played.loc[played["margin"].idxmax()] if len(played) else None

        # Walk the bracket game by game, in the order it was actually played.
        all_games = _playoff_games(p)
        walk = [g for g in all_games if g["played"]]
        ids = [g["id"] for g in walk]
        cur = matchup if matchup in ids else (p.config.get("final")
                                              if p.config.get("final") in ids
                                              else (ids[-1] if ids else None))
        i = ids.index(cur) if cur in ids else -1
        ctx.update({
            "playoff": p,
            "champion": p.champion or "undecided",
            "games": played["matchup_id"].nunique(),
            "top": (f"{top['points']:.1f} · {top['team']}" if top is not None else "—"),
            "blow": (f"+{blow['margin']:.1f} · {blow['team']}" if blow is not None else "—"),
            "walk": walk,
            "matchup": cur,
            "prev": ids[i - 1] if i > 0 else None,
            "next": ids[i + 1] if 0 <= i < len(ids) - 1 else None,
            "step": (i + 1) if i >= 0 else 0,
            "n_steps": len(ids),
            "summary": sm.playoff_summary(p).to_dict("records"),
            "stats": sm.playoff_stats(d["playoffs"], scope).to_dict("records"),
            "rules": _grouped_rules(p.config.get("scoring_settings", {})),
            "n_rules": len(p.config.get("scoring_settings", {})),
        })
        return tpl.TemplateResponse(request, "tab_playoffs.html", ctx)
    else:
        return HTMLResponse("<p class='empty'>Unknown tab.</p>", status_code=404)

    return tpl.TemplateResponse(request, "tab_charts.html", ctx)


@app.get("/report")
def report(league: str = DEFAULT_LEAGUE, season: str | None = None):
    """Generate and download the standalone HTML season report.

    Rendered on demand (it draws ~19 charts), so it takes a few seconds -- the
    file it returns is fully self-contained and needs the server for nothing
    afterwards.
    """
    import tempfile
    d, s, key = pick(league, season)
    tmp = tempfile.NamedTemporaryFile(suffix=".html", delete=False)
    tmp.close()
    sm.season_report(s, tmp.name, seasons=d["seasons"], playoffs=d["playoffs"])
    fname = f"{s.name}_{key}_report.html".replace(" ", "_")
    return FileResponse(tmp.name, media_type="text/html", filename=fname)


@app.get("/health")
def health():
    return {"ok": True, "league": DEFAULT_LEAGUE}
